Homework_Lesson6 is done
Nadya101/Teaching pull request #3
Opened 2021-09-13 22:56 UTC by Nadya101

2021-09-14 09:59 UTC, nickrogracher commented on src/lesson6_task1/Transport.java
> +    static Scanner scanner = new Scanner(System.in, StandardCharsets.UTF_8);
@Nadya101  Нашла причину?☺☺

2021-09-14 10:08 UTC, Nadya101 commented on src/lesson6_task1/Transport.java
> +    static Scanner scanner = new Scanner(System.in, StandardCharsets.UTF_8);
нашла, а здесь удобно комментировать, спасибо)

2021-09-14 10:52 UTC, nickrogracher requested changes

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/Transport.java
> +        this.technicalChar = technicalChar;
powerKW и technicalChar не передаются в конструктор. Что ты тогда присввамваешь этим значениям на объекте?
```suggestion
    public Transport(int powerHours, int maxSpeed, String brand, float weight) {
        this.powerKW = powerKW;
        this.maxSpeed = maxSpeed;
        this.weight = weight;
        this.brand = brand;
```

>###  _В условии для Transport только 4 обязательных поля, а не 6!_ <br><p>&#160;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;↓<p>


- Мощность(в лошадиных силах)
- Максимальная скорость(км/ч
- Масса (кг)
- Марка( например: Audi, BMW , Boing, Airbus, Scania , МАЗ и т.д. )

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/Transport.java
> +    }
А это зачем? Ты же определила, что косяк просто в кодировке. На английском ждут ".", а на русском - ","

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/CargoTransport.java
> +public class CargoTransport extends LandTransport {
![image](https://user-images.githubusercontent.com/48067169/133240904-b7050840-b5bf-4780-9cce-f7777fbeaee4.png)
@Nadya101  Для названия на английском, лучше использовать google translate

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/CargoTransport.java
> +        if (cargoWeight < this.loadingCapacity) System.out.println("Грузовик загружен.");
```suggestion
        if (cargoWeight < this.loadingCapacity) {
             System.out.println("Грузовик загружен.");ntln("Грузовик загружен.");
       }         
```
@Nadya101 Все таки лучше отделять фигурными скобками. Без них лучше в Kotlin, ошибся немного

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/LightTransport.java
> +        this.way = way;
@Nadya101 И снова 
```suggestion
        this.way = someFloatValue;  //например 12,3f
```
ты не передала в параметры конструктора значение way, оно вообще не должно было компилироваться....

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/LightTransport.java
> +        return this.technicalChar;
@Nadya101  Можно укоротить и избежать лишнего создания новой переменной
```suggestion
        return "Марка " + this.brand + ":\n-Мощность " + this.powerHours + " лошадиных сил;\n-Мощность " + getPowerKw() + " кВ;\n" +
                "-Максимальная скорость " + this.maxSpeed + " км/ч;\n-Масса " + this.weight + " кг;\n" +
                "-Количество колёс " + this.countOfWheels + ";\n-Расход топлива " + this.fuelConsumption + " л/100км;\n" +
                "-Тип кузова - " + this.bodyworkType + ";\n-Кол-во пассажиров " + this.countPassengers + " человек.\n";
```

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/LightTransport.java
> +    public void getWay() {
@Nadya101  /* метод который будет  **### _ПРИНИМАТЬ_** время..
```suggestion
  
    public void getWay(float time) {
```

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/LightTransport.java
> +        return way * (this.fuelConsumption / 100);
@Nadya101 Программа правда компилируется??
```suggestion
    private float getTotalFuelConsumption(float way) {
        return way * (this.fuelConsumption / 100);
```

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/LightTransport.java
> +
@Nadya101 слишком много пустых строк ненужных, убери

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/AirTransport.java
> +                        float wingspan, int minRunwayLength) {              // поля экзепляров етого класа
@Nadya101  не критично, улыбнуло, но стоит грамматику даже в коментариях проверять☺☺
```suggestion
                        float wingspan, int minRunwayLength) {              // поля экзепляров Этого класа
```

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/PassengerTransport.java
> +public class PassengerTransport extends AirTransport {
@Nadya101 не так английском будет=)
![image](https://user-images.githubusercontent.com/48067169/133243552-aaf85e5f-ffe8-4732-a155-1c5b98e07874.png)

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/PassengerTransport.java
> +        return this.technicalChar;
@Nadya101 сокращаем код :
```suggestion
        return "Марка " + this.brand + ":\n-Мощность " + this.powerHours + " лошадиных сил;\n-Мощность " + getPowerKw() + " кВ;\n" +
                "-Максимальная скорость " + this.maxSpeed + " км/ч;\n-Масса " + this.weight + " кг;\n" +
                "-Размах крыльев " + this.wingspan + " м;\n-Минимальная длина взлётно-посадочной полосы для взлёта " + this.minRunwayLength + " м;\n" +
                "-Кол-во пассажиров " + this.countPassengers + ";\n-" + checkBusinessClass() + ".\n";
```

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/PassengerTransport.java
> +        else return "Бизнес класc отсутствует";
@Nadya101 используй фигурные скобки

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/PassengerTransport.java
> +    public void checkCapacity() {
@Nadya101 Почему один метод private, а второй public? Чем обусловен выбор?

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/PassengerTransport.java
> +        else System.out.println("Вам нужен самолет побольше.");
@Nadya101 фигурные скобочки

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/MilitaryTransport.java
> +public class MilitaryTransport extends AirTransport {
@Nadya101  Лучше было бы назвать MilitaryAirTransport (Военный Воздушный Транспорт)

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/MilitaryTransport.java
> +        this.countRocket = countRocket;
@Nadya101  нету входного параметра для countRocket
```suggestion
    public MilitaryTransport(int powerHours, String brand, int maxSpeed, int minRunwayLength,
                             float weight, float wingspan, int countRocket, boolean isCatapult,
                             int countRocket) {
        super(powerHours, maxSpeed, brand, weight, wingspan, minRunwayLength);
        this.countRocket = countRocket;
```

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/MilitaryTransport.java
> +        return this.technicalChar;
@Nadya101 Сокращаем код
```suggestion
        return "Марка " + this.brand + ":\n-Мощность " + this.powerHours + " лошадиных сил;\n-Мощность " + getPowerKw() + " кВ;\n" +
                "-Максимальная скорость " + this.maxSpeed + " км/ч;\n-Масса " + this.weight + " кг;\n" +
                "-Размах крыльев " + this.wingspan + " м;\n-Минимальная длина взлётно-посадочной полосы для взлёта " + this.minRunwayLength + " м;" +
                "\n-" + checkCatapultSystem() + "\n-Количество ракет на борту - " + this.countRocket + " штук.\n";
```

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/MilitaryTransport.java
> +        else return "Системы катапультирования отсутсвует;";
@Nadya101 используй фигурные скобки

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/MilitaryTransport.java
> +        else System.out.println("Боеприпасы отсутствуют.");
@Nadya101 используй фигурные скобки

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/MilitaryTransport.java
> +        else System.out.println("У вас нет такой системы.");
@Nadya101 используй фигурные скобки

2021-09-14 10:52 UTC, nickrogracher commented on src/lesson6_task1/MilitaryTransport.java
> +    }
@Nadya101 💯 👍

2021-09-14 15:15 UTC, Nadya101 commented on src/lesson6_task1/LightTransport.java
> +        return way * (this.fuelConsumption / 100);
Правда все работало. Но я делаю как нужно!

2021-09-14 15:17 UTC, Nadya101 commented on src/lesson6_task1/PassengerTransport.java
> +    public void checkCapacity() {
checkCapacity нужно из мейну вызвать,  а checkBusinessClass только для использование в этом классе в методе getDescription

2021-09-14 15:17 UTC, Nadya101 commented on src/lesson6_task1/Transport.java
> +    }
Я хотела чтобы работало и так, и так. Но уже исправила и остальные ошибки, все согласно комментариям. Спасибо)

2021-09-14 21:34 UTC, Nadya101 commented on src/lesson6_task1/LightTransport.java
> +        return way * (this.fuelConsumption / 100);
![getway_method](https://user-images.githubusercontent.com/44065623/133336758-cf12e83f-543e-49bc-bf7d-ed08a7eb6989.PNG)
ранее сохраненный код

2021-09-15 14:39 UTC, Nadya101 commented on src/lesson6_task1/Transport.java
> +        this.technicalChar = technicalChar;
Исправила, оставила только 4 поля как в задании.

2021-09-15 14:41 UTC, Nadya101 commented on src/lesson6_task1/CargoTransport.java
> +public class CargoTransport extends LandTransport {
Исправлено, назван класс _public class FreightTransport_.

2021-09-15 14:43 UTC, Nadya101 commented on src/lesson6_task1/CargoTransport.java
> +        if (cargoWeight < this.loadingCapacity) System.out.println("Грузовик загружен.");
- [ ] Сделано)

2021-09-15 14:46 UTC, Nadya101 commented on src/lesson6_task1/LightTransport.java
> +        this.way = way;
Удалила все **поля** из конструктора, значение которых **не вносим** при создании экземпляров.

2021-09-15 14:51 UTC, Nadya101 commented on src/lesson6_task1/LightTransport.java
> +        return this.technicalChar;
Исправила, странно почему я так сразу не сделала &#128528;

2021-09-15 14:53 UTC, Nadya101 commented on src/lesson6_task1/LightTransport.java
> +    public void getWay() {
Исправила тоже, но здесь сканер удалила. Заделала метод который принимает готовые значение _float time_

2021-09-15 14:54 UTC, Nadya101 commented on src/lesson6_task1/LightTransport.java
> +
Уже удалила!

2021-09-15 14:56 UTC, Nadya101 commented on src/lesson6_task1/PassengerTransport.java
> +public class PassengerTransport extends AirTransport {
Поменяла название класса на _public class CivilAirTransport_ ))

2021-09-15 14:58 UTC, Nadya101 commented on src/lesson6_task1/PassengerTransport.java
> +        else System.out.println("Вам нужен самолет побольше.");
Поставила)

2021-09-15 15:03 UTC, Nadya101 commented on src/lesson6_task1/MilitaryTransport.java
> +        return this.technicalChar;
Исправлено)

2021-09-15 15:06 UTC, Nadya101 commented on src/lesson6_task1/MilitaryTransport.java
> +        else return "Системы катапультирования отсутсвует;";
Хорошо, точно больше не буду забывать о них))

2021-09-15 15:27 UTC, Nadya101 commented on src/lesson6_task1/AirTransport.java
> +                        float wingspan, int minRunwayLength) {              // поля экзепляров етого класа
Исправлено &#129318;

2021-09-15 15:32 UTC, Nadya101 commented on src/lesson6_task1/PassengerTransport.java
> +        else return "Бизнес класc отсутствует";
Исправила и в этом месте тоже

2021-09-15 15:33 UTC, Nadya101 commented on src/lesson6_task1/MilitaryTransport.java
> +        else System.out.println("Боеприпасы отсутствуют.");
Хорошо)

2021-09-15 15:33 UTC, Nadya101 commented on src/lesson6_task1/MilitaryTransport.java
> +        else System.out.println("У вас нет такой системы.");
Хорошо)

2021-09-15 15:53 UTC, Nadya101 commented
@nickrogracher Код исправлен, но не уверена должна ли я resolve conversation натискать? Здесь закрыть запрос нужно?

2021-09-28 18:22 UTC, nickrogracher approved these changes

2021-09-28 18:22 UTC, merged